library(dplyr)
library(readr)
library(ggplot2)
library(reshape2)

rawdf <- read_csv("C:/Users/rober//Google Drive/Code_scripts/R/forthefuckofit/New_model/all_regseason_cleaned_1996-2017.csv")
tourn <- read_csv("C:/Users/rober/Google Drive/Code_scripts/R/forthefuckofit/New_model/all_tournament_wins_1996-2017.csv")


uraw_school <- data.frame(School = unique(rawdf$School))

utourn_school <- data.frame(School = unique(c(tourn$team1, tourn$team2)))

diff <- setdiff(utourn_school, uraw_school) %>% arrange() 

other_diff <- setdiff(uraw_school, utourn_school) %>% arrange() 

# rename team1
new_team1 <- tourn$team1
new_team1 <- ifelse(new_team1 == "BYU"	,	"Brigham Young", new_team1)
new_team1 <- ifelse(new_team1 == "Central Connecticut"	,	"Central Connecticut State", new_team1)
new_team1 <- ifelse(new_team1 == "Detroit"	,	"Detroit Mercy", new_team1)
new_team1 <- ifelse(new_team1 == "ETSU"	,	"East Tennessee State", new_team1)
new_team1 <- ifelse(new_team1 == "LIU-Brooklyn"	,	"Long Island University", new_team1)
new_team1 <- ifelse(new_team1 == "LSU"	,	"Louisiana State", new_team1)
new_team1 <- ifelse(new_team1 == "Ole Miss"	,	"Mississippi", new_team1)
new_team1 <- ifelse(new_team1 == "Penn"	,	"Pennsylvania", new_team1)
new_team1 <- ifelse(new_team1 == "Pitt"	,	"Pittsburgh", new_team1)
new_team1 <- ifelse(new_team1 == "SMU"	,	"Southern Methodist", new_team1)
new_team1 <- ifelse(new_team1 == "Southern Miss"	,	"Southern Mississippi", new_team1)
new_team1 <- ifelse(new_team1 == "St. Joseph's"	,	"Saint Joseph's", new_team1)
new_team1 <- ifelse(new_team1 == "St. Peter's"	,	"Saint Peter's", new_team1)
new_team1 <- ifelse(new_team1 == "UCF"	,	"Central Florida", new_team1)
new_team1 <- ifelse(new_team1 == "UConn"	,	"Connecticut", new_team1)
new_team1 <- ifelse(new_team1 == "UCSB"	,	"UC-Santa Barbara", new_team1)
new_team1 <- ifelse(new_team1 == "UIC"	,	"Illinois-Chicago", new_team1)
new_team1 <- ifelse(new_team1 == "UMass"	,	"Massachusetts", new_team1)
new_team1 <- ifelse(new_team1 == "UMBC"	,	"Maryland-Baltimore County", new_team1)
new_team1 <- ifelse(new_team1 == "UNC"	,	"North Carolina", new_team1)
new_team1 <- ifelse(new_team1 == "UNLV"	,	"Nevada-Las Vegas", new_team1)
new_team1 <- ifelse(new_team1 == "USC"	,	"Southern California", new_team1)
new_team1 <- ifelse(new_team1 == "UTEP"	,	"Texas-El Paso", new_team1)
new_team1 <- ifelse(new_team1 == "UTSA"	,	"Texas-San Antonio", new_team1)
new_team1 <- ifelse(new_team1 == "VCU"	,	"Virginia Commonwealth", new_team1)

# rename team2
new_team2 <- tourn$team2
new_team2 <- ifelse(new_team2 == "BYU"	,	"Brigham Young", new_team2)
new_team2 <- ifelse(new_team2 == "Central Connecticut"	,	"Central Connecticut State", new_team2)
new_team2 <- ifelse(new_team2 == "Detroit"	,	"Detroit Mercy", new_team2)
new_team2 <- ifelse(new_team2 == "ETSU"	,	"East Tennessee State", new_team2)
new_team2 <- ifelse(new_team2 == "LIU-Brooklyn"	,	"Long Island University", new_team2)
new_team2 <- ifelse(new_team2 == "LSU"	,	"Louisiana State", new_team2)
new_team2 <- ifelse(new_team2 == "Ole Miss"	,	"Mississippi", new_team2)
new_team2 <- ifelse(new_team2 == "Penn"	,	"Pennsylvania", new_team2)
new_team2 <- ifelse(new_team2 == "Pitt"	,	"Pittsburgh", new_team2)
new_team2 <- ifelse(new_team2 == "SMU"	,	"Southern Methodist", new_team2)
new_team2 <- ifelse(new_team2 == "Southern Miss"	,	"Southern Mississippi", new_team2)
new_team2 <- ifelse(new_team2 == "St. Joseph's"	,	"Saint Joseph's", new_team2)
new_team2 <- ifelse(new_team2 == "St. Peter's"	,	"Saint Peter's", new_team2)
new_team2 <- ifelse(new_team2 == "UCF"	,	"Central Florida", new_team2)
new_team2 <- ifelse(new_team2 == "UConn"	,	"Connecticut", new_team2)
new_team2 <- ifelse(new_team2 == "UCSB"	,	"UC-Santa Barbara", new_team2)
new_team2 <- ifelse(new_team2 == "UIC"	,	"Illinois-Chicago", new_team2)
new_team2 <- ifelse(new_team2 == "UMass"	,	"Massachusetts", new_team2)
new_team2 <- ifelse(new_team2 == "UMBC"	,	"Maryland-Baltimore County", new_team2)
new_team2 <- ifelse(new_team2 == "UNC"	,	"North Carolina", new_team2)
new_team2 <- ifelse(new_team2 == "UNLV"	,	"Nevada-Las Vegas", new_team2)
new_team2 <- ifelse(new_team2 == "USC"	,	"Southern California", new_team2)
new_team2 <- ifelse(new_team2 == "UTEP"	,	"Texas-El Paso", new_team2)
new_team2 <- ifelse(new_team2 == "UTSA"	,	"Texas-San Antonio", new_team2)
new_team2 <- ifelse(new_team2 == "VCU"	,	"Virginia Commonwealth", new_team2)

# rename winner
new_winner <- tourn$winner
new_winner <- ifelse(new_winner == "BYU"	,	"Brigham Young", new_winner)
new_winner <- ifelse(new_winner == "Central Connecticut"	,	"Central Connecticut State", new_winner)
new_winner <- ifelse(new_winner == "Detroit"	,	"Detroit Mercy", new_winner)
new_winner <- ifelse(new_winner == "ETSU"	,	"East Tennessee State", new_winner)
new_winner <- ifelse(new_winner == "LIU-Brooklyn"	,	"Long Island University", new_winner)
new_winner <- ifelse(new_winner == "LSU"	,	"Louisiana State", new_winner)
new_winner <- ifelse(new_winner == "Ole Miss"	,	"Mississippi", new_winner)
new_winner <- ifelse(new_winner == "Penn"	,	"Pennsylvania", new_winner)
new_winner <- ifelse(new_winner == "Pitt"	,	"Pittsburgh", new_winner)
new_winner <- ifelse(new_winner == "SMU"	,	"Southern Methodist", new_winner)
new_winner <- ifelse(new_winner == "Southern Miss"	,	"Southern Mississippi", new_winner)
new_winner <- ifelse(new_winner == "St. Joseph's"	,	"Saint Joseph's", new_winner)
new_winner <- ifelse(new_winner == "St. Peter's"	,	"Saint Peter's", new_winner)
new_winner <- ifelse(new_winner == "UCF"	,	"Central Florida", new_winner)
new_winner <- ifelse(new_winner == "UConn"	,	"Connecticut", new_winner)
new_winner <- ifelse(new_winner == "UCSB"	,	"UC-Santa Barbara", new_winner)
new_winner <- ifelse(new_winner == "UIC"	,	"Illinois-Chicago", new_winner)
new_winner <- ifelse(new_winner == "UMass"	,	"Massachusetts", new_winner)
new_winner <- ifelse(new_winner == "UMBC"	,	"Maryland-Baltimore County", new_winner)
new_winner <- ifelse(new_winner == "UNC"	,	"North Carolina", new_winner)
new_winner <- ifelse(new_winner == "UNLV"	,	"Nevada-Las Vegas", new_winner)
new_winner <- ifelse(new_winner == "USC"	,	"Southern California", new_winner)
new_winner <- ifelse(new_winner == "UTEP"	,	"Texas-El Paso", new_winner)
new_winner <- ifelse(new_winner == "UTSA"	,	"Texas-San Antonio", new_winner)
new_winner <- ifelse(new_winner == "VCU"	,	"Virginia Commonwealth", new_winner)


